# Copyright (c) 2025 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    import: submanifests

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: nfed
      url-base:  https://github.com/circuitdojo

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.2.0
      import: true
    - name: nfed
      remote: nfed
      repo-path: nrf9160-feather-examples-and-drivers
      revision: v3.2.x
